authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('register/', views.register, name='register'),
]

core/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView

app_name = 'core'


urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('home/', views.home, name='home'),
    path('login/', LoginView.as_view(template_name='core/welcome.html'), name='login'),
]

faceverse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('groups/', include('group_management.urls')),
    path('profile/', include('user_management.urls')),
    path('post_management', include('post_management.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.db import models

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('user_management:profile', username=user.username)
    else:
        form = UserCreationForm()
    return render(request, 'authentication/register.html', {'form': form})

authentication/templates/authentication/register.html
<!DOCTYPE html>
<html lang="pl">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>faceverse | rejestracja</title>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap"
			rel="stylesheet"
		/>
		{% load static %}
		<link rel="stylesheet" href="{% static 'css/register.css' %}" />
	</head>
	<body>
		<div class="register">
			<h1 class="register__title">Rejestracja</h1>
			<form method="post" class="register__form">
				{% csrf_token %}
				<div class="register__form__group">
					{{ form.username.label_tag }} {{ form.username }}
				</div>

				<div class="register__form__group">
					{{ form.password1.label_tag }} {{ form.password1 }}
				</div>
				<div class="register__form__group">
					{{ form.password2.label_tag }} {{ form.password2 }}
				</div>
				<button type="submit" class="register__form__submit-button">
					Zarejestruj się
				</button>
				<p class="register__login">
					Masz już konto?
					<a href="{% url 'core:welcome' %}" class="register__login-link"
						>Zaloguj się</a
					>
				</p>
			</form>
		</div>
	</body>
</html>