core/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView

app_name = 'core'


urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('home/', views.home, name='home'),
    path('login/', LoginView.as_view(template_name='core/welcome.html'), name='login'),
]

faceverse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('groups/', include('group_management.urls')),
    path('profile/', include('user_management.urls')),
    path('post_management', include('post_management.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group_management/urls.py
from django.urls import path
from . import views

app_name = 'group_management'

urlpatterns = [
    path('', views.groups, name='groups'),
    path('<slug:group_slug>/', views.group_detail, name='group_detail'),
    path('<slug:group_slug>/edit/', views.edit_group, name='edit_group'),
]

post_management/urls.py
from django.urls import path
from . import views

app_name = 'post_management'

urlpatterns = [
    path('create_post/', views.create_post, name='create_post'),
    path('like_post/', views.like_post, name='like_post'),
    path('post/<int:post_id>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('groups/<str:group_slug>/create_post/', views.create_group_post, name='create_group_post'),
]

user_management/urls.py
from django.urls import path
from . import views


app_name = 'user_management'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('friends/', views.friends, name='friends'),
    path('logout/', views.logout_view, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow_user/<str:username>/', views.follow_user, name='follow_user'),
    path('check_follow_status/<str:username>/', views.check_follow_status, name='check_follow_status'),

]

user_management/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(max_length=500, blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', default='default.png', blank=True, null=True)


class Follow(models.Model):
    follower = models.ForeignKey(User, related_name='following', on_delete=models.CASCADE)
    followed = models.ForeignKey(User, related_name='followers', on_delete=models.CASCADE)

    class Meta:
        unique_together = ('follower', 'followed')

user_management/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile


class ProfileForm(forms.ModelForm):
    profile_image = forms.ImageField(widget=forms.FileInput, required=False)

    class Meta:
        model = Profile
        fields = ['bio', 'profile_image']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username']

user_management/views.py
from django.contrib import messages
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from post_management.forms import PostForm
from post_management.models import Post
from user_management.forms import ProfileForm, UserEditForm
from user_management.models import Follow


@login_required(login_url='core:welcome')
def profile(request):
    return render(request, 'user_management/profile.html')


@login_required(login_url='core:welcome')
def friends(request):
    return render(request, 'user_management/friends.html')


def logout_view(request):
    logout(request)
    return redirect('core:welcome')


@login_required(login_url='core:welcome')
def profile(request, username):
    user = get_object_or_404(User, username=username)
    profile_user = get_object_or_404(User, username=username)
    user_posts = Post.objects.filter(author=user, group__isnull=True).order_by('-created_at')
    user_groups = user.user_groups.all()
    form = PostForm()
    is_own_profile = (request.user == user)

    context = {
        'user': user,
        'posts': user_posts,
        'user_groups': user_groups,
        'is_own_profile': is_own_profile,
        'form': form,
        'profile_user': profile_user
    }
    return render(request, 'user_management/profile.html', context)


@login_required
def edit_profile(request):
    if request.method == 'POST':
        user_form = UserEditForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Twój profil został zaktualizowany.')
            return redirect('user_management:profile', username=request.user.username)
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileForm(instance=request.user.profile)

    return render(request, 'user_management/edit_profile.html', {
        'user_form': user_form,
        'profile_form': profile_form
    })


@login_required
@require_POST
def follow_user(request, username):
    user_to_follow = get_object_or_404(User, username=username)

    if request.user != user_to_follow:
        follow, created = Follow.objects.get_or_create(follower=request.user, followed=user_to_follow)
        if not created:
            follow.delete()
            action = 'unfollowed'
        else:
            action = 'followed'
    else:
        action = 'self'

    followers_count = user_to_follow.followers.count()
    return JsonResponse({'status': 'ok', 'action': action, 'followers_count': followers_count})


@login_required
def check_follow_status(request, username):
    user_to_check = get_object_or_404(User, username=username)
    is_following = Follow.objects.filter(follower=request.user, followed=user_to_check).exists()
    return JsonResponse({'is_following': is_following})

user_management/templates/user_management/edit_profile.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>faceverse | {{ user.username }}</title>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap"
			rel="stylesheet"
		/>
		{% load static %}
		<link rel="stylesheet" href="{% static 'css/edit_profile.css' %}" />
	</head>
<body>
    <h1>Edytuj Profil</h1>
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <!-- Wyświetlenie błędów formularza -->
    {{ user_form.non_field_errors }}
    {{ profile_form.non_field_errors }}

    <!-- Pola formularza UserEditForm -->
    <div>
        <label for="id_username">Nazwa użytkownika:</label>
        {{ user_form.username.errors }}
        {{ user_form.username }}
    </div>

    <!-- Pola formularza ProfileForm -->
    <div>
        <label for="id_bio">Bio:</label>
        {{ profile_form.bio.errors }}
        {{ profile_form.bio }}
    </div>
    <div>
        <label for="id_profile_image">Zdjęcie profilowe:</label>
        {{ profile_form.profile_image.errors }}
        {{ profile_form.profile_image }}
    </div>

    <button type="submit">Zapisz zmiany</button>
</form>

<a href="{% url 'user_management:profile' user.username %}">Powrót do profilu</a>
</body>
</html>

user_management/templates/user_management/profile.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<title>faceverse | {{ user.username }}</title>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap"
			rel="stylesheet"
		/>
		{% load static %}
		<link rel="stylesheet" href="{% static 'css/profile.css' %}" />
	</head>
<body>

   <header class="top-nav">
			<div class="top-nav__logo">faceverse</div>
			<nav class="top-nav__links">
                    <a href="{% url 'user_management:logout' %}">Wyloguj</a>

				<a href="{% url 'core:home' %}" class="top-nav__link">Strona główna</a>
				<a href="{% url 'group_management:groups' %}" class="top-nav__link"
					>Grupy</a
				>
				<a
					href="{% url 'user_management:profile' request.user.username %}"
					class="top-nav__link"
					>Mój profil</a
				>
			</nav>
		</header>

     <!-- Profile Section -->
    <div class="profile-section">
        <div class="profile-header">
            <img src="{{ user.profile.profile_image.url }}" alt="Profile Picture" class="profile-picture">
            <div class="profile-info">
                <h1>{{ user.username }}</h1>

                <p id="followers-count">Followerzy: {{ user.followers.count }}</p>
                <p id="following-count">Followuje: {{ user.following.count }}</p>
                 {% if not is_own_profile %}
    <button class="follow-button" data-username="{{ user.username }}">
        {% if request.user in user.followers.all %}
            Przestań Obserwować
        {% else %}
            Obserwuj
        {% endif %}
    </button>
{% endif %}

            </div>
        </div>

        <!-- User Groups List -->
        <div class="user-groups">
            <h5> <p>{{ user.profile.bio }}</p></h5>
            <h3>            <a href="{% url 'user_management:edit_profile' %}">Edytuj Profil</a>
</h3>
            <h3>Grupy użytkownika:</h3>

                {% for group in user.user_groups.all %}

                    <p><a href="{% url 'group_management:group_detail' group.slug %}">{{ group.name }}</a></p>
                {% empty %}
                    <p>Nie znaleziono grup</p>
                {% endfor %}

        </div>
<script>
document.addEventListener('DOMContentLoaded', function() {
    var username = "{{ user.username }}";
    var followButton = document.querySelector('.follow-button');

    // Wygeneruj URL z placeholderem w Django, a potem zamień go w JavaScript
    var checkFollowStatusUrl = "{% url 'user_management:check_follow_status' 'REPLACE_USERNAME' %}".replace('REPLACE_USERNAME', username);

    // Sprawdzanie stanu obserwacji przy ładowaniu strony
    fetch(checkFollowStatusUrl, {
        headers: {
            'X-CSRFToken': '{{ csrf_token }}'
        }
    })
    .then(response => response.json())
    .then(data => {
        if (data.is_following) {
            followButton.textContent = 'Przestań Obserwować';
        } else {
            followButton.textContent = 'Obserwuj';
        }
    })
    .catch(error => console.error('Error:', error));

    // Obsługa kliknięcia przycisku
    followButton.addEventListener('click', function() {
        var followUserUrl = "{% url 'user_management:follow_user' 'REPLACE_USERNAME' %}".replace('REPLACE_USERNAME', username);

        fetch(followUserUrl, {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.status === 'ok') {
                if (data.action === 'followed') {
                    followButton.textContent = 'Przestań Obserwować';
                } else if (data.action === 'unfollowed') {
                    followButton.textContent = 'Obserwuj';
                }
                document.getElementById('followers-count').textContent = 'Liczba obserwujących: ' + data.followers_count;
            }
        })
        .catch(error => console.error('Error:', error));
    });
});
</script>



    {% if is_own_profile %}
        <div>

            <form method="post" action="{% url 'post_management:create_post' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Opublikuj</button>
    </form>
        </div>
    {% endif %}

    <div class="posts-section">
    {% block content %}
    {% for post in posts %}
        <div class="post">
            <p>{{ post.author }} <small>{{ post.created_at }}</small></p>
            <p>{{ post.content }}</p>

            <button id="like-button-{{ post.id }}" type="button" onclick="likePost({{ post.id }});">Lubię to!</button>
            <span id="like-count-{{ post.id }}">{{ post.likes.count }}</span><br>

            {% for comment in post.comments.all %}
                {{ comment.author.username }} <span>  </span> {{ comment.created_at }}
                <p>{{ comment.content }}</p>
            {% endfor %}

            <form action="{% url 'post_management:add_comment_to_post' post.id %}" method="post">
                {% csrf_token %}
                <input type="text" name="content" placeholder="Dodaj komentarz...">
                <button type="submit">Komentuj</button>
            </form>
        </div>
    {% empty %}
        <p>{% if is_own_profile %}Nie znaleziono Twoich postów.{% else %}Nie znaleziono postów użytkownika {{ user.username }}.{% endif %}</p>
    {% endfor %}
{% endblock %}

    </div>
    <script src="{% static 'js/likes.js' %}"></script>
    <script>
        var likePostUrl = '{% url "post_management:like_post" %}';
        var csrfToken = '{{ csrf_token }}';
    </script>
</body>
</html>