authentication/urls.py
from django.urls import path
from . import views

app_name = 'authentication'

urlpatterns = [
    path('register/', views.register, name='register'),
]

core/urls.py
from . import views
from django.urls import path
from django.contrib.auth.views import LoginView

app_name = 'core'


urlpatterns = [
    path('', views.welcome, name='welcome'),
    path('home/', views.home, name='home'),
    path('login/', LoginView.as_view(template_name='core/welcome.html'), name='login'),
]

faceverse/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('groups/', include('group_management.urls')),
    path('profile/', include('user_management.urls')),
    path('post_management', include('post_management.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

group_management/urls.py
from django.urls import path
from . import views

app_name = 'group_management'

urlpatterns = [
    path('', views.groups, name='groups'),
    path('<slug:group_slug>/', views.group_detail, name='group_detail'),
    path('<slug:group_slug>/edit/', views.edit_group, name='edit_group'),
]

post_management/urls.py
from django.urls import path
from . import views

app_name = 'post_management'

urlpatterns = [
    path('create_post/', views.create_post, name='create_post'),
    path('like_post/', views.like_post, name='like_post'),
    path('post/<int:post_id>/comment/', views.add_comment_to_post, name='add_comment_to_post'),
    path('groups/<str:group_slug>/create_post/', views.create_group_post, name='create_group_post'),
]

user_management/urls.py
from django.urls import path
from . import views


app_name = 'user_management'

urlpatterns = [
    path('', views.profile, name='profile'),
    path('friends/', views.friends, name='friends'),
    path('logout/', views.logout_view, name='logout'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),
    path('<str:username>/', views.profile, name='profile'),
    path('follow_user/<str:username>/', views.follow_user, name='follow_user'),
    path('check_follow_status/<str:username>/', views.check_follow_status, name='check_follow_status'),

]

core/models.py
from django.db import models

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from group_management.models import Group
from post_management.forms import PostForm
from post_management.models import Post


def welcome(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('core:home')
    else:
        form = AuthenticationForm()

    return render(request, 'core/welcome.html', {'form': form})


@login_required(login_url='core:welcome')
def home(request):
    my_groups = Group.objects.filter(members=request.user)
    group_posts = Post.objects.filter(group__in=my_groups)
    followed_user_posts = Post.objects.filter(
        author__in=User.objects.filter(followers__follower=request.user),
        group__isnull=True
    )
    all_posts = group_posts | followed_user_posts | Post.objects.filter(author=request.user)
    user_posts = all_posts.distinct().order_by('-created_at')
    form = PostForm()

    context = {
        'form': form,
        'posts': user_posts
    }

    return render(request, 'core/home.html', context)

core/templates/core/home.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta
			name="viewport"
			content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
		/>
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<title>faceverse | Strona Główna</title>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap"
			rel="stylesheet"
		/>
		{% load static %}
		<link rel="stylesheet" href="{% static 'css/home.css' %}" />
	</head>
	<body
		data-like-post-url="{% url 'post_management:like_post' %}"
		data-csrf-token="{{ csrf_token }}"
	>
		{% if user.is_authenticated %}
		<header class="top-nav">
			<div class="top-nav__logo">faceverse</div>
			<nav class="top-nav__links">
				<a href="{% url 'core:home' %}" class="top-nav__link">Strona główna</a>
				<a href="{% url 'group_management:groups' %}" class="top-nav__link"
					>Grupy</a
				>
				<a
					href="{% url 'user_management:profile' user.username %}"
					class="top-nav__link"
					>Mój profil</a
				>
			</nav>
		</header>
		<aside class="sidebar">
            <h3 class="sidebar__text">Twoje grupy:</h3>
			{% for group in user.user_groups.all %}
			<p class="sidebar__text"><a
					href="{% url 'group_management:group_detail' group_slug=group.slug %}"
					>{{ group.name }}</a
				></p>
				
        </p>
			{% empty %}
			<p>{{ user.username }} nie należy do żadnych grup.</p>
			{% endfor %}
			
		</aside>

		<main class="main-content">
			<form
				method="post"
				action="{% url 'post_management:create_post' %}"
				class="post-form"
			>
				{% csrf_token %}
				<div class="post-form__header">
					{% if user.profile.profile_image %}
					<img
						src="{{ user.profile.profile_image.url }}"
						alt="Profile picture of {{ user.username }}"
						class="user-thumbnail"
					/>
					{% endif %}

					<p class="post-form__username">{{ user.username }}</p>
					{{ form.content.label_tag }} {{ form.content }}
				</div>
				<div class="post-form__actions"></div>
				<button type="submit" class="post-form__submit">Opublikuj post</button>
			</form>

			{% for post in posts %}
			<div class="post">
				{% if post.author.profile.profile_image %}
				<img
					src="{{ post.author.profile.profile_image.url }}"
					alt="Zdjęcie profilowe {{ post.author.username }}"
					class="profile-thumbnail"
				/>
				{% endif %}
				<p>
					<a href="{% url 'user_management:profile' post.author.username %}"
						>{{ post.author }}</a
					>
					<small>{{ post.created_at }}</small>
				</p>
				<p>{{ post.content }}</p>

				{% if post.group %}
				<p>
					Grupa:
					<a
						href="{% url 'group_management:group_detail' group_slug=post.group.slug %}"
						>{{ post.group.name }}</a
					>
				</p>
				{% endif %}

				<button
					id="like-button-{{ post.id }}"
					class="like-button"
					type="button"
					onclick="likePost({{ post.id }});"
				>
					Lubię to!
				</button>
				<span class="like-count" id="like-count-{{ post.id }}"
					>{{ post.likes.count }}</span
				><br />

				{% for comment in post.comments.all %}
				<div class="comment">
					{% if comment.author.profile.profile_image %}
					<img
						src="{{ comment.author.profile.profile_image.url }}"
						alt="Zdjęcie profilowe {{ comment.author.username }}"
						class="profile-thumbnail"
					/>
					{% endif %}
					<p>
						<a
							href="{% url 'user_management:profile' comment.author.username %}"
							>{{ comment.author.username }}</a
						>
						<span>{{ comment.created_at }}</span>
					</p>
					<p>{{ comment.content }}</p>
				</div>
				{% endfor %}

				<form
					action="{% url 'post_management:add_comment_to_post' post.id %}"
					method="post"
				>
					{% csrf_token %}
					<input type="text" name="content" placeholder="Dodaj komentarz..." />
					<button type="submit">Komentuj</button>
				</form>
			</div>
			{% empty %}
			<p>Brak postów do wyświetlenia.</p>
			{% endfor %} {% else %}
			<p>Nie jesteś zalogowany.</p>
			{% endif %}
		</main>

		<script>
			var likePostUrl = '{% url "post_management:like_post" %}'
			var csrfToken = "{{ csrf_token }}"
		</script>
		<script src="{% static 'js/likes.js' %}"></script>
	</body>
</html>

core/templates/core/welcome.html
<!DOCTYPE html>
<html lang="pl">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>faceverse | logowanie</title>
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;700&display=swap"
			rel="stylesheet"
		/>
		{% load static %}
		<link rel="stylesheet" href="{% static 'css/welcome.css' %}" />
	</head>
	<body>
		<div class="welcome-page">
			<div class="welcome-page__header">
				<h1 class="welcome-page__title">faceverse</h1>
				<p>
					Lorem ipsum dolor sit amet consectetur adipisicing elit. Officiis,
					eveniet.
				</p>
			</div>
			<div class="welcome-page__login-form">
				<h2 class="welcome-page__login-title">Logowanie</h2>
				<form method="post" action="{% url 'core:welcome' %}" class="form">
					{% csrf_token %}
					<div class="form__group">{{ form.as_p }}</div>
					<button type="submit" class="form__submit-button">Zaloguj się</button>
				</form>
				<p class="welcome-page__register">
					Nie masz konta?
					<a
						href="{% url 'authentication:register' %}"
						class="welcome-page__register-link"
						>Zarejestruj się</a
					>
				</p>
			</div>
		</div>
	</body>
</html>